%-----------------------------------------------------------------------------%
% MiniZinc standard library.
%-----------------------------------------------------------------------------%
% This file contains built-in operations that can be expressed in MiniZinc,
% and so are not implemented as true built-ins within the compiler.

% (Currently there are none.)

% Include solver-specific redefinitions for any FlatZinc built-ins.
%
include "redefinitions.mzn"
