/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTArrayLiteral extends SimpleNode {
  public ASTArrayLiteral(int id) {
    super(id);
  }

  public ASTArrayLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8fe6339f3fc9d7f98f0e39c65cc7173 (do not edit this line) */
