/* Generated By:JJTree: Do not edit this line. ASTBoolTiExprTail.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTBoolTiExprTail extends SimpleNode {
  public ASTBoolTiExprTail(int id) {
    super(id);
  }

  public ASTBoolTiExprTail(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=488953c84413d8b2e560e8c80fc5d237 (do not edit this line) */
