/* Generated By:JJTree: Do not edit this line. ASTConstraint.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTConstraint extends SimpleNode {
  public ASTConstraint(int id) {
    super(id);
  }

  public ASTConstraint(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58feaab29a26508ccb44f227db1b8d36 (do not edit this line) */
