/* Generated By:JJTree: Do not edit this line. ASTConstraintItems.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTConstraintItems extends SimpleNode {
  public ASTConstraintItems(int id) {
    super(id);
  }

  public ASTConstraintItems(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=994cf993b44497931ae9bf8d2100a285 (do not edit this line) */
