/* Generated By:JJTree: Do not edit this line. ASTIdAnns.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTIdAnns extends SimpleNode {
  public ASTIdAnns(int id) {
    super(id);
  }

  public ASTIdAnns(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=275f6a9410cc5e6d91c5b556b16b14de (do not edit this line) */
