/* Generated By:JJTree: Do not edit this line. ASTmodel.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTmodel extends SimpleNode {
  public ASTmodel(int id) {
    super(id);
  }

  public ASTmodel(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=541e0080ffe0a5c706509c07b461c241 (do not edit this line) */
