/* Generated By:JJTree: Do not edit this line. ASTModelEnd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTModelEnd extends SimpleNode {
  public ASTModelEnd(int id) {
    super(id);
  }

  public ASTModelEnd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2789b8408dbb069b5425372f4bbcced6 (do not edit this line) */
