/* Generated By:JJTree: Do not edit this line. ASTSetTiExprTail.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTSetTiExprTail extends SimpleNode {
  public ASTSetTiExprTail(int id) {
    super(id);
  }

  public ASTSetTiExprTail(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fed735bfaf9e7e60eed2c24bf0c0636a (do not edit this line) */
