/* Generated By:JJTree: Do not edit this line. ASTSolveItem.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTSolveItem extends SimpleNode {
  public ASTSolveItem(int id) {
    super(id);
  }

  public ASTSolveItem(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e4c9ea6d26ca727de8301e513591fca (do not edit this line) */
