/* Generated By:JJTree: Do not edit this line. ASTVarDeclItems.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package JaCoP.fz;

public
class ASTVarDeclItems extends SimpleNode {
  public ASTVarDeclItems(int id) {
    super(id);
  }

  public ASTVarDeclItems(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efd1094d55854015f0c6a66d1d0c6b60 (do not edit this line) */
