/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package JaCoP.fz;

public interface ParserTreeConstants
{
  public int JJTMODEL = 0;
  public int JJTVOID = 1;
  public int JJTVARDECLITEMS = 2;
  public int JJTCONSTRAINTITEMS = 3;
  public int JJTMODELEND = 4;
  public int JJTVARDECLITEM = 5;
  public int JJTCONSTRAINT = 6;
  public int JJTCONSTELEM = 7;
  public int JJTSOLVEITEM = 8;
  public int JJTSOLVEKIND = 9;
  public int JJTBOOLTIEXPRTAIL = 10;
  public int JJTINTTIEXPRTAIL = 11;
  public int JJTSETTIEXPRTAIL = 12;
  public int JJTANNEXPR = 13;
  public int JJTSCALARFLATEXPR = 14;
  public int JJTINTFLATEXPR = 15;
  public int JJTVARIABLEEXPR = 16;
  public int JJTSOLVEEXPR = 17;
  public int JJTINTLITERALS = 18;
  public int JJTSETLITERAL = 19;
  public int JJTARRAYLITERAL = 20;
  public int JJTANNOTATION = 21;


  public String[] jjtNodeName = {
    "model",
    "void",
    "VarDeclItems",
    "ConstraintItems",
    "ModelEnd",
    "VarDeclItem",
    "Constraint",
    "ConstElem",
    "SolveItem",
    "SolveKind",
    "BoolTiExprTail",
    "IntTiExprTail",
    "SetTiExprTail",
    "AnnExpr",
    "ScalarFlatExpr",
    "IntFlatExpr",
    "VariableExpr",
    "SolveExpr",
    "IntLiterals",
    "SetLiteral",
    "ArrayLiteral",
    "Annotation",
  };
}
/* JavaCC - OriginalChecksum=bd593dd33df0eb01ccc102f14fd1471e (do not edit this line) */
