package org.jcp.jsr331.samples;

import javax.constraints.*;

// Generated by Kathryn Glenn Francis <k.francis@pgrad.unimelb.edu.au>

public class ExampleCompareTo {

	public static void main(String[] args) {
		
		Problem p = ProblemFactory.newProblem("TestCompareTo");
        Var x = p.variable("X", 0, 3);
        Var y = p.variable("Y", 0, 3);
        Var cost = p.variable("Cost", 0, 10);

//      You cannot use the method "compareTo" directly but rather to post "implies" constraints
//        if (x.compareTo(y) == 1) {
//            cost = x.minus(y);
//        } else {
//            cost = x.plus(y);
//        }
        Constraint more = p.linear(x, ">", y);
        Constraint lessOrEqual = p.linear(x, "<=", y);
        Constraint minus = p.linear(cost, "=", x.minus(y));
        Constraint plus = p.linear(cost, "=", x.plus(y));
        more.implies(minus).post();  //p.postIfThen(more, minus);
        lessOrEqual.implies(plus).post();
        
        p.log("=== Find solution");
        Solver solver = p.getSolver();
        Solution solution = solver.findOptimalSolution(Objective.MAXIMIZE, cost);
        solution.log();
	}

}